### ISSUE TITLE
Stop using engine's private API in tests

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-list#101]
Follow-up #98.

After introducing https://github.com/ckeditor/ckeditor5-engine/issues/738, tests still use private API because it's hard to replace it with the writer.

https://github.com/ckeditor/ckeditor5-list/blob/70e6a4ffa1fb4765f734de29e4a418b31cac4725/src/converters.js#L423

and

https://github.com/ckeditor/ckeditor5-list/blob/70e6a4ffa1fb4765f734de29e4a418b31cac4725/src/converters.js#L450

after replacing with

```js
conversionApi.writer.remove( child );
```

throws an error:

```
        TypeError: parent.getPath is not a function
            at Function.createFromParentAndOffset (webpack:///packages/ckeditor5-engine/src/model/position.js:740:0 <- build/.automated-tests/entry-point.js:1826:23)
            at Function.createBefore (webpack:///packages/ckeditor5-engine/src/model/position.js:720:0 <- build/.automated-tests/entry-point.js:1806:15)
            at Writer.remove (webpack:///packages/ckeditor5-engine/src/model/writer.js:507:0 <- build/.automated-tests/entry-point.js:53329:80)
            at UpcastDispatcher.cleanList (webpack:///packages/ckeditor5-list/src/converters.js:423:0 <- build/.automated-tests/entry-point.js:58427:26)
            at UpcastDispatcher.fire (webpack:///packages/ckeditor5-utils/src/emittermixin.js:196:0 <- build/.automated-tests/entry-point.js:2160:29)
            at UpcastDispatcher._convertItem (webpack:///packages/ckeditor5-engine/src/conversion/upcastdispatcher.js:212:0 <- build/.automated-tests/entry-point.js:33281:9)
            at UpcastDispatcher._convertChildren (webpack:///packages/ckeditor5-engine/src/conversion/upcastdispatcher.js:243:0 <- build/.automated-tests/entry-point.js:33312:24)
            at UpcastDispatcher.<anonymous> (webpack:///packages/ckeditor5-engine/src/conversion/upcast-converters.js:547:36 <- build/.automated-tests/entry-point.js:28350:54)
            at UpcastDispatcher.fire (webpack:///packages/ckeditor5-utils/src/emittermixin.js:196:0 <- build/.automated-tests/entry-point.js:2160:29)
            at UpcastDispatcher._convertItem (webpack:///packages/ckeditor5-engine/src/conversion/upcastdispatcher.js:216:0 <- build/.automated-tests/entry-point.js:33285:9)
```

for:

* ListEditing flat lists setting data clears incorrect elements
* ListEditing flat lists setting data clears whitespaces
* ListEditing nested lists setting data mixed lists deep structure, white spaces, incorrect content, empty items

On the occasion, we could other parts of the code which use engine's private API:

* https://github.com/ckeditor/ckeditor5-list/pull/98/files#diff-181a641e45476f54a783a7ad41ed6f5bR782 (`_setAttribute`)
* https://github.com/ckeditor/ckeditor5-list/pull/98/files#diff-181a641e45476f54a783a7ad41ed6f5bR801 (`_appendChildren`)
* https://github.com/ckeditor/ckeditor5-list/pull/98/files#diff-9570d3f589559b4f36f63a0cc738740dR3628
* https://github.com/ckeditor/ckeditor5-list/pull/98/files#diff-9570d3f589559b4f36f63a0cc738740dR3678 (`_insertChildren`)

**Comment by pomek** [comment]
I updated a little the ticket. Tests are fixed so now we use private API only in sources.

**Comment by szymonkups** [comment]
Quoting @pjasiun:
> `upcastConversionDispatcher` fires `viewClenaup` event that should have a writer (currently does not), so data cleanup should be done there.

**Comment by Reinmar** [comment]
Isn't this the same situation as in https://github.com/ckeditor/ckeditor5-list/blob/d2023267caa88eb383b1fab773e137c233cf5b8d/src/converters.js#L455-L462 where we have the writer?
